import type { Theme } from '../../../../shared/types/theme';

export const nexoraLight: Theme = {
  id: 'nexora-light',
  name: 'Nexora Light',
  isPreset: true,
  isReadOnly: true,
  colors: {
    bg: {
      base: '#ffffff',
      elevated: '#f8fafc',
      overlay: '#f1f5f9',
      input: '#ffffff',
      tooltip: '#f1f5f9',
    },
    surface: {
      primary: '#f1f5f9',
      secondary: '#e2e8f0',
      tertiary: '#cbd5e1',
      hover: '#e2e8f0',
      active: '#3b82f6',
      disabled: '#f1f5f9',
    },
    text: {
      primary: '#0f172a',
      secondary: '#475569',
      muted: '#64748b',
      disabled: '#94a3b8',
      accent: '#3b82f6',
      inverse: '#ffffff',
    },
    accent: {
      primary: '#3b82f6',
      secondary: '#8b5cf6',
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#06b6d4',
    },
    border: {
      subtle: '#f1f5f9',
      default: '#e2e8f0',
      strong: '#cbd5e1',
      focus: '#3b82f6',
    },
    semantic: {
      string: '#dc2626',
      number: '#2563eb',
      boolean: '#7c3aed',
      date: '#16a34a',
      null: '#64748b',
      primaryKey: '#d97706',
      foreignKey: '#0891b2',
      index: '#9333ea',
      connectionActive: '#22c55e',
      connectionInactive: '#64748b',
      modified: '#3b82f6',
      deleted: '#ef4444',
      new: '#22c55e',
    },
  },
  typography: {
    fontFamily: {
      base: 'Inter, system-ui, Avenir, Helvetica, Arial, sans-serif',
      mono: 'JetBrains Mono, Fira Code, Monaco, Consolas, monospace',
    },
    fontSize: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
    },
  },
  layout: {
    borderRadius: {
      sm: '0.25rem',
      base: '0.5rem',
      lg: '0.75rem',
      xl: '1rem',
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      base: '1rem',
      lg: '1.5rem',
      xl: '2rem',
    },
  },
  monacoTheme: {
    base: 'vs',
    inherit: true,
    themeName: 'GitHub Light',
  },
};
