import { createContext } from "react";
import type { Settings, SettingsContextType } from "../features/settings";

export type {
  AiProvider,
  AppLanguage,
  CopyFormat,
  ERDiagramLayout,
  PluginConfig,
  Settings,
  SettingsContextType,
} from "../features/settings";

export const SettingsContext = createContext<SettingsContextType | undefined>(
  undefined,
);

export const DEFAULT_SETTINGS: Settings = {
  resultPageSize: 500,
  language: "auto",
  displayTimezone: "auto",
  fontFamily: "System",
  fontSize: 14,
  resultColorByType: false,
  resultTypeColors: {},
  stickyColumnHeaders: true,
  aiEnabled: false,
  aiProvider: null,
  aiModel: null,
  aiCustomModels: undefined,
  aiOllamaPort: 11434,
  aiCustomOpenaiUrl: "",
  aiCustomOpenaiModel: "",
  loggingEnabled: true,
  maxLogEntries: 1000,
  copyFormat: "csv",
  csvDelimiter: ",",
  csvIncludeHeaders: true,
  erDiagramDefaultLayout: "LR",
  editorFontFamily: "JetBrains Mono",
  editorFontSize: 14,
  editorLineHeight: 1.5,
  editorTabSize: 2,
  editorWordWrap: true,
  editorShowLineNumbers: true,
  editorAcceptSuggestionOnEnter: true,
  pingInterval: 30,
  queryHistoryMaxEntries: 500,
  autoConnectLastConnection: true,
  startMaximized: false,
  aiAuditEnabled: true,
  aiAuditMaxEntries: 5000,
  aiSessionGapMinutes: 10,
  mcpReadonlyDefault: false,
  mcpReadonlyConnections: [],
  mcpApprovalMode: "writes_only",
  mcpApprovalTimeoutSeconds: 120,
  mcpPreflightExplain: true,
  mcpApprovalAlwaysOnTop: true,
  mcpApprovalNotifySound: true,
};
