import { createHash } from "node:crypto";
import { cpSync, existsSync, mkdirSync, readFileSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { basename, dirname, resolve } from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(readFileSync(resolve(root, "package.json"), "utf8")) as { version: string };
const build = resolve(root, ".tmp/build");
const staging = resolve(root, ".tmp/staging");
const output = resolve(root, ".tmp/package");
const name = `nexora-create-plugin-${pkg.version}.tgz`;
if (!existsSync(resolve(build, "cli.js"))) throw new Error("Fresh .tmp/build/cli.js is required before staging");
rmSync(output, { recursive: true, force: true });
rmSync(staging, { recursive: true, force: true });
mkdirSync(output, { recursive: true });
mkdirSync(resolve(staging, "dist"), { recursive: true });
cpSync(build, resolve(staging, "dist"), { recursive: true });
for (const path of ["templates", "README.md", "LICENSE"]) cpSync(resolve(root, path), resolve(staging, path), { recursive: true });
const packageJson = JSON.parse(readFileSync(resolve(root, "package.json"), "utf8")) as Record<string, unknown>;
delete packageJson.scripts;
delete packageJson.devDependencies;
writeFileSync(resolve(staging, "package.json"), `${JSON.stringify(packageJson, null, 2)}\n`);
const packed = execFileSync("pnpm", ["pack", "--pack-destination", output], { cwd: staging, encoding: "utf8", env: { ...process.env, npm_config_ignore_scripts: "true" } }).trim();
const packedPath = resolve(output, basename(packed));
const target = resolve(output, name);
if (packedPath !== target) renameSync(packedPath, target);
const digest = createHash("sha256").update(readFileSync(target)).digest("hex");
writeFileSync(`${target}.sha256`, `${digest}  ${name}\n`);
rmSync(staging, { recursive: true, force: true });
