name: Publish to Winget

on:
  workflow_dispatch:

jobs:
  winget-publish:
    if: ${{ vars.ENABLE_STORE_PUBLISH == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Submit to Winget
        uses: vedantmgoyal9/winget-releaser@v2
        with:
          identifier: Nexora.Nexora
          installers-regex: '_x64-setup\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
